stages:
    - build
    - test
    - coverage

compile:
    stage: build
    script:
      - cmake CMakeLists.txt
      - make -j7

tests:
    stage: test
    script:
      - cmake -DCMAKE_BUILD_TYPE=DEBUG CMakeLists.txt
      - make -j7
      - ./bin/unit_tests
      - ./bin/cu_unit_tests

coverage:
    stage: coverage
    script:
      - cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=DEBUG -DCOVERAGE=1
      - make -j7
      - mkdir cov
      - kcov --include-path=./src cov/ bin/unit_tests
      - kcov --include-path=./src cov/ bin/cu_unit_tests
      - cat cov/kcov-merged/coverage.json
