stages:
    - build
    - test
    - coverage

compile:
    stage: build
    script:
      - cmake cmakelists.txt
      - make -j4

tests:
    stage: test
    dependencies:
      - compile
    script:
      - ./bin/unit_tests
      - ./bin/cu_unit_tests

coverage:
    stage: coverage
    dependencies:
      - compile
    script:
      - mkdir cov
      - kcov --include-path=./src cov/ bin/unit_tests
      - kcov --include-path=./src cov/ bin/cu_unit_tests
      - cat cov/kcov-merged/coverage.json
